# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.CreateUserRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :profile,
    :identities
  ]

  @type t :: %__MODULE__{
    :profile => KindeSDK.Model.CreateUserRequestProfile.t | nil,
    :identities => [KindeSDK.Model.CreateUserRequestIdentitiesInner.t] | nil
  }

  alias KindeSDK.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profile, :struct, KindeSDK.Model.CreateUserRequestProfile)
     |> Deserializer.deserialize(:identities, :list, KindeSDK.Model.CreateUserRequestIdentitiesInner)
  end
end

