# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.CreateUserRequestProfile do
  @moduledoc """
  Basic information required to create a user
  """

  @derive Jason.Encoder
  defstruct [
    :given_name,
    :family_name
  ]

  @type t :: %__MODULE__{
    :given_name => String.t | nil,
    :family_name => String.t | nil
  }

  def decode(value) do
    value
  end
end

