# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.CreateUserRequestIdentitiesInner do
  @moduledoc """
  The result of the user creation operation
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :details
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :details => KindeSDK.Model.CreateUserRequestIdentitiesInnerDetails.t | nil
  }

  alias KindeSDK.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:details, :struct, KindeSDK.Model.CreateUserRequestIdentitiesInnerDetails)
  end
end

