# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.Organization do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :name,
    :is_default
  ]

  @type t :: %__MODULE__{
    :code => String.t | nil,
    :name => String.t | nil,
    :is_default => boolean() | nil
  }

  def decode(value) do
    value
  end
end

