# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.RemoveOrganizationUsers200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :message,
    :users_added
  ]

  @type t :: %__MODULE__{
    :message => String.t | nil,
    :users_added => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

