# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.UserIdentity do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :result
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :result => KindeSDK.Model.UserIdentityResult.t | nil
  }

  alias KindeSDK.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:result, :struct, KindeSDK.Model.UserIdentityResult)
  end
end

