# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.User do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :email,
    :last_name,
    :first_name,
    :is_suspended
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :email => String.t | nil,
    :last_name => String.t | nil,
    :first_name => String.t | nil,
    :is_suspended => boolean() | nil
  }

  def decode(value) do
    value
  end
end

